#Uncomment as needed
#baseurl = "Your site URL"
languageCode = "en-us"
Title = "Ataraxia Sound"
# Copyright notice. This is displayed in the footer.
copyright = "&copy; Copyright notice"
theme = "potato-dark"

[params]
  paginate = 10
  description = "Damià Lahoz Tarres"
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "Your Twitter username"
  facebook = "Your Facebook username"
  instagram = "Your Instagram username"
  github = "Your GitHub username"
  gitlab = "Your GitLab username"
  npm = "Your npm username"
  
  # You need to provide the mastodon instance domain name as well as the username
  mastodon = "mastodon-instance-domain.com/@your_username"
  # Disqus shortname
  disqus = ""
  # Google Analytics API key.
  ga_api_key = "Your Google Analytics tracking id"
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[[menu.main]]
    name = "Meditaciones"
    url = "/meditaciones"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

[[menu.main]]
    name = "Música"
    url = "/musica"
    weight = 4

[[menu.main]]
    name = "Poemas"
    url = "/poemas"
    weight = 3

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"